Big merge
WildCodeSchool-2024-02/JS-lyon-0224-P2-lazy_flicks pull request #27
Opened 2024-04-25 14:15 UTC by Thienthienko

PR Dev to main : Les US : 
US 16 jusqu'à US 25

2024-04-26 07:46 UTC, wildmatthieu requested changes

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/App.jsx
> +      <div className={`app ${lightMode && "light-theme"}`}>
soyez explicites dans vos conditions

lightMode === truc &&
lightMode === true &&
lightMode === false &&
...

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Body/Body.jsx
> +    if (selectedGenre && selectedType) {
soyez explicites dans vos conditions : 
selectedGenre === true &&
selectedGenre === false &&
... ?

idem pour selectedType ;)

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Body/Body.jsx
> +          onClick={isSectionVisible ? handleSearchAgain : handleSearch}
soyez explicites sur vos conditions : isSectionVisible

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Description/Description.jsx
> +    if (randomMovie) {
explicitez la condition : 
randomMovies

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Description/Description.jsx
> +  const movieElement = randomMovie && (
explicitez la condition : 
randomMovie

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/MovieType/MovieType.jsx
> +    if (randomMovie) {
explicitez la condition : 
randomMovie

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/MovieType/MovieType.jsx
> +  const randomMovieElement = randomMovie && (
explicitez la condition : 
randomMovie

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Series/Series.jsx
> +        if (!response.ok) {
explicitez la condition : 
!response.ok === ?
!response.ok !== ?

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Series/Series.jsx
> +    if (randomSerie) {
explicitez la condition : 
randomSerie

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Series/Series.jsx
> +  const randomSerieElement = randomSerie && (
explicitez la condition : 
randomSerie

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/Team/Team.css
> +@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap");
utilisez une police en local au lieu de la récupérer systématiquement depuis un serveur distant. 
Autrement dit : téléchargez la police, callez la qque part dans votre dossier assets et chargez la ensuite en css toujours en utilisant l'instruction `@import url("...");`

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/TopRated/TopRated.jsx
> +    if (topRatedChecked) {
explicitez la condition : 
topRatedChecked

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/TopRated/TopRated.jsx
> +          setMovies(randomMovie ? [randomMovie] : []);
explicitez la condition : 
randomMovie

2024-04-26 07:46 UTC, wildmatthieu commented on client/src/components/TopRated/TopRated.jsx
> +      {topRatedChecked && <div>{movieElements}</div>}
explicitez la condition : 
topRatedChecked

2024-04-26 15:28 UTC, wildmatthieu requested changes

2024-04-26 15:28 UTC, wildmatthieu commented on client/src/components/Body/Body.jsx
> +        {isSectionVisible !== false && selectedGenre && (
condition à expliciter : 
selectedGenre === ?

2024-04-26 15:28 UTC, wildmatthieu commented on client/src/components/Body/Body.jsx
> +        {isSectionVisible !== false && selectedGenre && (
condition à expliciter : selectedGenre

2024-04-26 15:28 UTC, wildmatthieu commented on client/src/components/Description.css
>  .PicDescOver {
utiliser des noms de classes en camelCase 
donc pas de majuscule pour le premier caractere 

Par exemple : .PicDescOver
par 
.picDescOver

=> à appliquer aux autres classes de l'app

2024-04-26 15:28 UTC, wildmatthieu commented on client/src/components/Team/Team.css
> +.TeamContainer {
idem dans ce fichier, utiliser les camelCases pour le nom des classes en CSS, donc on ne commence pas par une majuscule ;)

2024-04-29 09:17 UTC, wildmatthieu requested changes

2024-04-29 09:17 UTC, wildmatthieu commented on client/src/components/Description/Description.jsx
> +  const movieElement = randomMovie ? (
explicitez vos conditions :) 
randomMovie === ?

2024-04-29 09:25 UTC, Thienthienko commented on client/src/components/Description/Description.jsx
> +  const movieElement = randomMovie ? (
La condition est explicité, il s'agit d'un ternaire
![Capture d'écran 2024-04-29 112521](https://github.com/WildCodeSchool-2024-02/JS-lyon-0224-P2-lazy_flicks/assets/159894955/56fb2154-af1a-4a06-9501-42951879d39e)

2024-04-29 09:38 UTC, wildmatthieu commented on client/src/components/Description/Description.jsx
> +  const movieElement = randomMovie ? (
vu avec Thien => code à compléter 
randomMovie === ?

2024-04-29 10:15 UTC, wildmatthieu requested changes

2024-04-29 10:15 UTC, wildmatthieu commented on client/src/components/Series/Series.jsx
> +        if (!response.ok === true) {
pour une meilleure lisibilité, je vous invite à écrire la condition comme suit : 

if(response.ok !== true)
=> ce qui se lit plus natuellement par : si reponse.ok n'est pas vrai ..

2024-04-29 11:01 UTC, wildmatthieu approved these changes

2024-04-29 11:01 UTC, merged